title: Waterfox.cz
description: Český rozcestník Waterfox

logo: /assets/img/waterfox-logo-128.png
show_downloads: false
google_analytics: UA-119108218-1

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE
  - README.md
